/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HCIce */

#ifndef _Included_HCIce
#define _Included_HCIce
#ifdef __cplusplus
extern "C" {
#endif
#undef HCIce_BUFFER_SIZE
#define HCIce_BUFFER_SIZE 131072L
/* Inaccessible static: LOG */
/*
 * Class:     HCIce
 * Method:    setSong
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HCIce_setSong
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HCIce
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HCIce__1init
  (JNIEnv *, jobject);

/*
 * Class:     HCIce
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HCIce__1close
  (JNIEnv *, jobject);

/*
 * Class:     HCIce
 * Method:    _initBroadcast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HCIce__1initBroadcast
  (JNIEnv *, jobject);

/*
 * Class:     HCIce
 * Method:    _endBroadcast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HCIce__1endBroadcast
  (JNIEnv *, jobject);

/*
 * Class:     HCIce
 * Method:    _broadcast
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_HCIce__1broadcast
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
