#! /bin/sh
#
# $Id: reinitdisk 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

# make sure all FSes are unmounted first
#
# copy this script to all servers then launch it in parallel.
# be sure to check the results

for disk in `cat /proc/partitions | awk '{ print $4 }' | grep -e '^hd[a-z]$'`
do

  #echo disk = $disk
  last_partition=`grep -e ${disk}[0-9] /proc/partitions | tail -1 | awk '{ print $4 }' | sed -r s/$disk\([0-9]+\)/\\\1/`
  #echo last_partition = $last_partition

  while [ -n "$last_partition" ]
  do

    if [ $last_partition -eq "1" ]
    then

      #echo last_partition is \"1\"
      fdisk /dev/$disk << EOF
d
w
EOF

    else

      #echo last_partition is not \"1\"
      fdisk /dev/$disk << EOF
d
$last_partition
w
EOF

    fi

    last_partition=`grep -e ${disk}[0-9] /proc/partitions | tail -1 | awk '{ print $4 }' | sed -r s/$disk\([0-9]+\)/\\\1/`
  #echo last_partition = $last_partition

  done

done

echo
cat /proc/partitions
echo done
