#! /bin/sh
#
# $Id: StoreRetrieve 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

# For running the StoreRetrieve test 

export PATH=/usr/lib/java/bin:/usr/local/java/bin/:$PATH

# use a logging properties file if we can find one
loggingproperties1=./logging.properties
loggingproperties2=/root/logging.properties
if [ -f $loggingproperties1 ]; then
    loggingoption="-Djava.util.logging.config.file=$loggingproperties1"
elif [ -f $loggingproperties2 ]; then
    loggingoption="-Djava.util.logging.config.file=$loggingproperties2"
else
    loggingoption=""
fi

TESTLIBPATH="/opt/honeycomb/tests/lib"
HCLIBPATH="/opt/honeycomb/lib"

java -classpath $TESTLIBPATH/honeycomb-test.jar:\
$HCLIBPATH/honeycomb.jar:\
$HCLIBPATH/honeycomb-xmlclient.jar \
$loggingoption \
  com.sun.honeycomb.test.sg.TestStoreRetrieve $*

