#!/bin/bash
#
# $Id: RunAuditSrv 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#
#
#  figure out LIB dir
#
ROOT=`dirname $0`
if [ "$ROOT" = "." ]; then
	ROOT=`pwd`
fi
ROOT=`dirname $ROOT`

LIB=$ROOT/lib
 
NETv20="bge1000"
NETv60="e1000g1000"
NET=unknown

# get host ip
echo
HOST=`ifconfig $NETv20 2>/dev/null | grep inet | awk '{print $2}'`
if [ $HOST ] ; then
	# echo got v20 interface $NETv20
        NET="$NETv20 (v20)"
else
	HOST=`ifconfig $NETv60  2>/dev/null | grep inet | awk '{print $2}'`
	if [ $HOST ] ; then
		# echo got v60 interface $NETv60
		NET="$NETv60 (v60)"
	else
		echo unsupported ifconfig interface
		exit 1
	fi
fi

# get path for java
. /etc/profile

echo net is $NET host is $HOST security is $LIB/security.policy

java -cp "$LIB/honeycomb-test.jar:$LIB/honeycomb-hctest.jar:$LIB/honeycomb-server.jar" \
        -server \
	-Djava.security.policy=$LIB/security.policy \
	-Djava.library.path=$LIB \
        -Djava.util.logging.config.file=$LIB/hc_logging.properties \
	-Djava.rmi.server.hostname=$HOST \
		com.sun.honeycomb.hctest.rmi.auditsrv.srv.AuditSrvServer
