#!/bin/bash
#
# $Id: RunClntSrv 11674 2007-12-03 18:35:10Z wr152514 $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#
#
#  figure out LIB dir
#
rm -rf /tmp/RunClntSrv.result

ROOT=`dirname $0`
if [ "$ROOT" = "." ]; then
        ROOT=`pwd`
fi
ROOT=`dirname $ROOT`

LIB=$ROOT/lib
 
# get hostname
HOST=`ifconfig eth0 | grep "inet addr:" | sed "s/inet addr://" | awk '{print $1}'`
# get path for java
. /etc/profile

echo host is $HOST security is $LIB/security.policy
#ls -l $LIB/security.policy

JARS="$LIB/honeycomb-test.jar:$LIB/honeycomb-hctest.jar:$LIB/honeycomb-client.jar:${LIB}/postgresql-8.1dev-400.jdbc3.jar"

java -cp $JARS -Xmx512m \
	-Djava.security.policy=$LIB/security.policy \
	-Djava.rmi.server.hostname=$HOST \
	-Dhctest.audit_dbhost=hc-dev3.sfbay.sun.com \
		com.sun.honeycomb.hctest.rmi.clntsrv.srv.ClntSrvServer

echo $? > /tmp/RunClntSrv.result
