#!/bin/bash
#
# $Id: qareport 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

# simple script to mail unsent test results for given branches
#
# needed: 
#
#   - a $HOME/.qadata/c_last.<BRANCH> file for each branch
#     containing last checkpoint time in this format:
#
#         2004-09-30 13:22:42
#
#   - 'qa' perlscript installed in path
#   - /usr/lib/perl5/site_perl/5.8.0/qadb.pm
#   - /usr/lib/perl5/site_perl/5.8.0/XML/Simple.pm
#

BRANCHES="HEAD CHARTER"

EMAIL=hc-sw@sun.com

for i in $BRANCHES ; do

	qa results -F "%d %R %I %T" -c $i -s > /tmp/qar.$$

	lines=`wc -l /tmp/qar.$$ | awk '{print $1}'`

	if test $lines -gt 2 ; then
		cat /tmp/qar.$$ |  mail -s "$i branch test results" $EMAIL
	fi
	/bin/rm -f /tmp/qar.$$

done

