#! /bin/bash
#
# $Id:$
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

#
# A utility to convert OIDs to different representations (internal/external,
# 1.0/1.1 OID formats).
#
# Before using this tool, make sure to look up the cell id on your cluster
# and pass it in as a command line argument to this tool, particularly if
# the conversion is an internal to external conversion.  Otherwise, it will
# default to cell id of 1.  This always assumes rule id of 1.
#
# Check the comments at the beginning of ConvertOid.java for more details.
#

export PATH=/usr/lib/java/bin:/usr/local/java/bin:/usr/local/lib:/usr/local/bin:$PATH

ROOT=`dirname $0`
if [ "$ROOT" = "." ]; then
    ROOT=`pwd`
fi

ROOT=`dirname $ROOT`
LIB=$ROOT/lib

java -classpath \
  $LIB/st5800-common.jar:$LIB/st5800-suitcase.jar:$LIB/st5800-server.jar:$LIB/jug.jar \
  -Duid.lib.path=$LIB \
  -Dhoneycomb.config.dir=$ROOT/etc \
 com.sun.honeycomb.suitcase.ConvertOid $*

