/*
 * SwingQueryLogger.java
 *
 * Created on June 15, 2004, 4:13 PM
 */

package com.sun.honeycomb.gui;

/**
 *
 * @author  sarnoud
 */
public abstract class SwingQueryLoggerForm extends javax.swing.JFrame implements com.sun.honeycomb.fs.QueryLogger {
    
    /** Creates new form SwingQueryLogger */
    public SwingQueryLoggerForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();

        setTitle("Query console");
        setBackground(new java.awt.Color(255, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        outputArea.setBackground(new java.awt.Color(255, 255, 204));
        outputArea.setColumns(100);
        outputArea.setEditable(false);
        outputArea.setRows(16);
        outputArea.setFocusable(false);
        outputArea.setName("null");
        jScrollPane1.setViewportView(outputArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    }//GEN-LAST:event_exitForm
    
    public abstract void logGetUniqueValues(String queryString, String key);    
    
    public abstract void logQuery(String queryString);
    
    protected void output(java.lang.String log) {
        outputArea.append(log+"\n");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputArea;
    // End of variables declaration//GEN-END:variables
    
}
