#!/bin/ksh -u
#
# $Id: copy_patches 10853 2007-05-19 02:50:20Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

PROGRAM=$(whence $0)
PROG_PATH=$(dirname $PROGRAM)
BINDIR=$PROG_PATH
PROG_NAME=$(basename $PROGRAM)

SRC=$1
DEST=$2

if [ ! -r $SRC/file/zones_patchlist.txt ] ; then
	echo "$PROG_NAME: unable to find $SRC/file/zones_patchlist.txt"
	exit 1
fi

if [ ! -d $DEST/solarisdvd.product/Solaris_10/UpgradePatches ] ; then
	mkdir $DEST/solarisdvd.product/Solaris_10/UpgradePatches
fi

if [ ! -r $SRC/pkgpool/SUNWcdbd/reloc/cdbuild/faspac ] ; then
	echo "$PROG_NAME: unable to find $SRC/pkgpool/SUNWcdbd/reloc/cdbuild/faspac"
	exit 1
fi

while read patchname ; do

	if [ ! -d $SRC/patch/$patchname ] ; then
		echo "$PROG_NAME: unable to find $SRC/patch/$patchname"
		exit 1
	fi	
	cd $SRC/patch
	echo "Copy patch $patchname to UpgradePatches"
	find $patchname -depth | cpio -pdum $DEST/solarisdvd.product/Solaris_10/UpgradePatches

done < $SRC/file/zones_patchlist.txt
       
$SRC/pkgpool/SUNWcdbd/reloc/cdbuild/faspac -p $DEST/solarisdvd.product/Solaris_10/UpgradePatches

exit 0
