#!/bin/bash
#
# $Id: rebootMasterLoop 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

JAVABIN=java

if [ -z $HCLIB ]; then 
    echo "Please set HCLIB to the location of the honeycomb libdir"
    exit 1
fi

if [ -z $1 ]; then
    echo "Please specify the cluster on which to perform error injection"
    exit 1
fi

CLUSTER=$1

if [ ! -e $HCLIB/honeycomb.jar ]; then
    echo "$HCLIB/honeycomb.jar does not exist; aborting"
    exit 1
fi

if [ ! -e $HCLIB/honeycomb-test.jar ]; then
    echo "$HCLIB/honeycomb-test.jar does not exist; aborting"
    exit 1
fi

echo "Using honeycomb.jar,honeycomb-test.jar at $HCLIB"

while [ 1 ]
do
    #OMGWTFBBQ?! I know there is a better way to do this, but I r sed n00b
    MASTER=`ssh admin@dev104-admin hwstat|grep " MASTER "|sed -e 's/^HCID-[0-9][0-9][0-9]-[0-9][0-9]//'|sed -e 's/[^0-9]//g'`
    echo "rebooting master node ${CLUSTER}-${MASTER}"
    echo ssh "${CLUSTER}-${MASTER} reboot"
    ssh ${CLUSTER}-${MASTER} reboot
    sleep 5m
done
