#!/bin/bash
#
# $Id: configure+make.sh 10853 2007-05-19 02:50:20Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

# This is an ant -> configure+make wrapper. It's called with a
# make command-line and current working dir of the package's source tree.
# The variables BUILDDIR, DIST, and BINDIR are understood. All temp
# files (files configure writes, .o files, etc.) are put under $BUILDDIR,
# and executables are copied into $BINDIR, with the intention of being
# run from $DIST.
#
# Example:
#     cd ntp-4.2.0
#     build.sh make BUILDDIR=foo BINDIR=bar install
#
# N.B.: If config.h.in is older than configure.in, the autotools
# will try to re-create ${SRCDIR}/config.h.in and ${SRCDIR}/configure.
# Avoid that.

[ "$#" != 0 ] || exit 0

SRCDIR="$PWD"
# We don't want stdout
exec >/dev/null

# Default build dir is the source directory itself
BUILDDIR=.

# Set all the variables on the command-line into the environment
for f in "$@"; do
    if echo "$f" | grep '='; then
        eval "$f"
    else
        OP="$f"
    fi
done

if [ "clean" = "$OP" ]; then
    eval "$@"
    exit 0
fi

# Files generated by configure, in order of timestamps
GENFILES="${SRCDIR}/configure ${SRCDIR}/config.h.in \
    ${BUILDDIR}/config.status ${BUILDDIR}/config.h"

# If we run configure from the build directory, all build files will be
# written under it
cd "${BUILDDIR}" || exit 1

if ! [ -f "${BUILDDIR}"/config.h ]; then
    "${SRCDIR}"/configure --prefix="${DIST}" --bindir="${BINDIR}" ||
        exit "$?"

    # This is the lousy hack to keep the Makefile from running
    # configure/autotools and modifying configure and config.h.in
    touch -c $GENFILES
fi

# Do it!
eval "$@"
