#!/bin/bash
#
# $Id: load 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

WHEREAMI=`cd \`dirname $0\`; pwd`
POSTRESULT=$WHEREAMI/../../../suitcase/src/script/postResult.sh

post () {
  $POSTRESULT -r skipped $*
}

post StoreData-TinyFiles load-store
post StoreData-LargeFiles load-store
post StoreData-MultiChunk load-store

post StoreDataWithMD-TinyFiles load-store
post StoreDataWithMD-LargeFiles load-store
post StoreDataWithMD-MultiChunk load-store

post AddMD-SmallMD load-store-metadata
post AddMD-LargeMD load-store-metadata
post AddMD-ManyRefs load-store-metadata

post RetrieveData-TinyFiles load-retrieve-data
post RetrieveData-LargeFiles load-retrieve-data
post RetrieveData-MultiChunk load-retrieve-data

post RetrieveMD-SmallMD load-retrieve-metadata
post RetrieveMD-LargeMD load-retrieve-metadata
post RetrieveMD-ManyRefs load-retrieve-metadata

post DeleteEverything load-delete

post QueryMD-SmallResultSet-ComplexQuery load-query
post QueryMD-SmallResultSet-SimpleQuery load-query
post QueryMD-LargeResultSet-ComplexQuery load-query
post QueryMD-LargeResultSet-SimpleQuery load-query
