#!/bin/bash
#
# $Id: node-faults 10858 2007-05-19 03:03:41Z bberndt $
#
# Copyright © 2008, Sun Microsystems, Inc.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#   # Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
#   # Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
#   # Neither the name of Sun Microsystems, Inc. nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



#

WHEREAMI=`cd \`dirname $0\`; pwd`
POSTRESULT=$WHEREAMI/../../../suitcase/src/script/postResult.sh

post () {
  $POSTRESULT -r skipped $*
}

EXTERNAL_OPS="store-data store-data+md store-md retrieve-data retrieve-md query delete"
INTERNAL_OPS="heal-frags scan-frags garbage-collect sysmd-repop extmd-repop"

# Step 1.
# Get a breadth of coverage on single-node faults for each external op using the 
# most mild type of fault, soft reboot.

for op in $EXTERNAL_OPS
do
  for node_type in non-servicing
  do
    for heal_frags_state in complete in-progress
    do 
      for fault_type in soft-reboot
      do
        for count in single-master single-non-master
        do
          post -p "node_type($node_type),count($count),heal_frags_state($heal_frags_state)" "NodeFault-$op-$fault_type" node-failure
        done
      done
    done
  done
done

for op in $INTERNAL_OPS
do
  for heal_frags_state in complete in-progress
  do 
    for fault_type in soft-reboot
    do
      for count in single-master single-non-master
      do
        post -p "count($count),heal_frags_state($heal_frags_state)" "NodeFault-$op-$fault_type" node-failure
      done
    done
  done
done
